version: '3'

services:
  php:
    build:
      context: ./php7.3
      dockerfile: dockerfile
    volumes:
      - ./php7.3/php.ini:/usr/local/etc/php/php.ini
      - ./html:/var/www/html
      - ./php7.3/000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - 1080:80
    links:
      - mysql:mysql
  mysql:
    image: mysql:5.7
    command:
      - --character-set-server=utf8
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 13306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=user
      - MYSQL_PASSWORD=test
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
    links:
      - mysql
    ports:
      - 4000:80
    volumes:
      - ./phpmyadmin/sessions:/sessions
