# FROM php:7.4-apache

# ENV http_proxy http://192.168.253.1:8080
# ENV https_proxy http://192.168.253.1:8080

# RUN export uid=1000 gid=1000 && \
# 	echo "user:x:${uid}:${gid}:user,,,::/bin/bash" >> /etc/passwd && \
# 	echo "user:x:${uid}:" >> /etc/group && \
# 	export COMPOSER_HOME=~/.composer

# RUN a2enmod rewrite
# RUN apt-get update && \
# 	apt-get install -y libicu-dev git unzip zlib1g-dev && \
# 	docker-php-ext-install pdo_mysql mysqli mbstring intl zip

FROM php:7.4-apache
COPY ./php.ini /usr/local/etc/php/

RUN apt-get update && \
    apt-get install -y --no-install-recommends apt-utils vim zip unzip zlib1g git libzip-dev libpng-dev libreoffice-calc libicu-dev && \
    docker-php-ext-install -j$(nproc) mysqli pdo_mysql zip gd && \
    apt-get clean && rm -rf /var/lib/apt/lists/* && \
    a2enmod rewrite

# RUN apt-get update \
# && apt-get install -y \
# zip \
# nano \
# libicu-dev \
# unzip \
# sudo

 RUN docker-php-ext-install intl